/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Calc */

#ifndef _Included_Calc
#define _Included_Calc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Calc
 * Method:    info
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Calc_info
  (JNIEnv *, jobject);

/*
 * Class:     Calc
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calc_add
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calc
 * Method:    subtract
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calc_subtract
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calc
 * Method:    multiply
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calc_multiply
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     Calc
 * Method:    divide
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_Calc_divide
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
